apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samplepod
    env: dev
  name: samplepod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplepod
      env: dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samplepod
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx
        