apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: valpod
  name: valpod
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: valpod
status:
  loadBalancer: {}